config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :teams
  resources :divisions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
    has_many :teams, dependent: :delete_all

    def self.playGame(teamA, teamB)
        scoreA = rand(100)
        scoreB = rand(100)

        if teamA.rating > teamB.rating
            scoreA *= 1 + teamA.rating - teamB.rating
        else
            scoreB *= 1 + teamB.rating - teamA.rating
        end

        winner = scoreA > scoreB ? teamA : teamB
        loser = scoreA > scoreB ? teamB : teamA
        return {
            winner: winner,
            loser: loser,
            score: [scoreA.to_s, scoreB.to_s].join(' / ')
        }
    end

    def self.playTournament(teams = nil)
        winners = []
        teams = self.teams if teams.nil?
        (0..teams.count-1).step(2) do |i|
            result = Division.playGame(teams[i], teams[i+1])
            winners << result[:winner]
        end
        return winners.first if winners.count == 1
        playTournament(winners)
    end

    def self.playAllDivision()
        divA = Division.playTournament Division.first.teams
        divB = Division.playTournament Division.last.teams
        
        winner = Division.playGame(divA, divB)[:winner]
        puts "The winner is team #{winner.name} from division #{winner.division.name}"
    end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :division
  has_many :players, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: [:show, :edit, :update, :destroy]

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:name)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:rating, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.players.destroy_all
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :rating, :division_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division, local: true) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% division.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Divisions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.name %></td>
        <td><%= link_to 'Show', division %></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cortex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.rating %></td>
        <td><%= player.team %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @player.rating %>
</p>

<p>
  <strong>Team:</strong>
  <%= @player.team %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>